import type { InvestmentAnalysis, Property } from '@/lib/types'
import { getSupabaseClient } from './client'

type OrganizationRow = {
  id: string
}

type ProfileRow = {
  organization_id: string | null
}

type PropertyInsertRow = {
  organization_id: string
  title: string
  city: string
  country: string
  address: string
  property_type: string
  status: string
  asking_price: number
  estimated_value: number
  area_sqm: number
  bedrooms: number
}

type OpportunityInsertRow = {
  organization_id: string
  property_id: string
  title: string
  stage: string
  priority: string
  estimated_roi: number | null
  expected_monthly_rent: number | null
  renovation_budget: number | null
  notes: string
}

export interface DealPersistenceResult {
  persisted: boolean
  organizationId?: string
  propertyId?: string
  opportunityId?: string
  noteId?: string
  reason?: string
}

const safeNumber = (value: unknown): number | null => {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return value
  }
  return null
}

const estimateRoi = (analysis: InvestmentAnalysis): number | null => {
  const appreciation = safeNumber(analysis.appreciationPotential.oneYear)
  const rentalYieldPct = safeNumber(analysis.rentalYieldEstimate.percentage)
  if (appreciation === null || rentalYieldPct === null) {
    return null
  }

  return Number((appreciation + rentalYieldPct).toFixed(2))
}

const mapPropertyToInsert = (organizationId: string, property: Property): PropertyInsertRow => ({
  organization_id: organizationId,
  title: property.title,
  city: property.city,
  country: property.country,
  address: property.district,
  property_type: property.propertyType,
  status: 'initial-analysis',
  asking_price: property.askingPrice,
  estimated_value: property.askingPrice,
  area_sqm: property.sizeSqm,
  bedrooms: property.bedrooms,
})

const mapOpportunityToInsert = (
  organizationId: string,
  propertyId: string,
  property: Property,
  analysis: InvestmentAnalysis,
): OpportunityInsertRow => ({
  organization_id: organizationId,
  property_id: propertyId,
  title: property.title,
  stage: 'initial-analysis',
  priority: 'medium',
  estimated_roi: estimateRoi(analysis),
  expected_monthly_rent: property.expectedRent ?? null,
  renovation_budget: safeNumber(analysis.renovationROI.estimatedCost),
  notes: `Generated by Deal Analyzer at ${analysis.analyzedAt}. Recommendation: ${analysis.recommendation}.`,
})

const resolveOrganizationId = async (): Promise<string> => {
  const client = getSupabaseClient()
  if (!client) {
    throw new Error('Supabase is not configured.')
  }

  try {
    const { data: userData } = await client.auth.getUser()
    const user = userData as { id?: string } | null
    if (user?.id) {
      const { data: profileData, error: profileError } = await client
        .from('profiles')
        .select('organization_id')
        .eq('id', user.id)
        .single()

      if (!profileError) {
        const profile = profileData as ProfileRow | null
        if (profile?.organization_id) {
          return profile.organization_id
        }
      }
    }
  } catch {
    // Fall through to first organization lookup.
  }

  const { data: orgData, error: orgError } = await client
    .from('organizations')
    .select('id')
    .order('created_at', { ascending: true })
    .limit(1)
    .single()

  if (orgError || !orgData) {
    throw new Error('No organization found. Create at least one organization row to enable Supabase persistence.')
  }

  const organization = orgData as OrganizationRow
  return organization.id
}

export const persistDealAnalyzerResult = async (
  property: Property,
  analysis: InvestmentAnalysis,
): Promise<DealPersistenceResult> => {
  const client = getSupabaseClient()
  if (!client) {
    return { persisted: false, reason: 'Supabase is unavailable. Running in local-only mode.' }
  }

  try {
    const organizationId = await resolveOrganizationId()

    const { data: propertyData, error: propertyError } = await client
      .from('properties')
      .insert([mapPropertyToInsert(organizationId, property)])
      .select('id')
      .single()

    if (propertyError || !propertyData) {
      throw new Error(propertyError?.message || 'Failed to create property.')
    }

    const propertyId = (propertyData as { id: string }).id

    const { data: opportunityData, error: opportunityError } = await client
      .from('opportunities')
      .insert([mapOpportunityToInsert(organizationId, propertyId, property, analysis)])
      .select('id')
      .single()

    if (opportunityError || !opportunityData) {
      throw new Error(opportunityError?.message || 'Failed to create opportunity.')
    }

    const opportunityId = (opportunityData as { id: string }).id

    const { data: noteData, error: noteError } = await client
      .from('notes')
      .insert([
        {
          organization_id: organizationId,
          opportunity_id: opportunityId,
          content: JSON.stringify(analysis),
        },
      ])
      .select('id')
      .single()

    if (noteError || !noteData) {
      throw new Error(noteError?.message || 'Failed to create analysis note snapshot.')
    }

    return {
      persisted: true,
      organizationId,
      propertyId,
      opportunityId,
      noteId: (noteData as { id: string }).id,
    }
  } catch (error) {
    return {
      persisted: false,
      reason: error instanceof Error ? error.message : 'Unknown persistence error.',
    }
  }
}
