import type { InvestmentAnalysis, Property } from '@/lib/types'
import { getSupabaseClient } from './client'
import { replaceAiFindingsForOpportunity } from './aiFindingsPersistence'

type ProfileRow = {
  id?: string
  user_id?: string
  organization_id: string | null
}

type AuthUser = {
  id: string
}

type PropertyInsertRow = {
  organization_id: string
  title: string
  city: string
  country: string
  address: string
  property_type: string
  status: string
  asking_price: number
  estimated_value: number
  area_sqm: number
  bedrooms: number
}

type OpportunityInsertRow = {
  organization_id: string
  property_id: string
  title: string
  stage: string
  priority: string
  estimated_roi: number | null
  expected_monthly_rent: number | null
  renovation_budget: number | null
  notes: string
}

export interface DealPersistenceResult {
  persisted: boolean
  organizationId?: string
  propertyId?: string
  opportunityId?: string
  noteId?: string
  reason?: string
}

const safeNumber = (value: unknown): number | null => {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return value
  }
  return null
}

const estimateRoi = (analysis: InvestmentAnalysis): number | null => {
  const appreciation = safeNumber(analysis.appreciationPotential.oneYear)
  const rentalYieldPct = safeNumber(analysis.rentalYieldEstimate.percentage)
  if (appreciation === null || rentalYieldPct === null) {
    return null
  }

  return Number((appreciation + rentalYieldPct).toFixed(2))
}

const mapPropertyToInsert = (organizationId: string, property: Property): PropertyInsertRow => ({
  organization_id: organizationId,
  title: property.title,
  city: property.city,
  country: property.country,
  address: property.district,
  property_type: property.propertyType,
  status: 'interested',
  asking_price: property.askingPrice,
  estimated_value: property.askingPrice,
  area_sqm: property.sizeSqm,
  bedrooms: property.bedrooms,
})

const mapOpportunityToInsert = (
  organizationId: string,
  propertyId: string,
  property: Property,
  analysis: InvestmentAnalysis,
): OpportunityInsertRow => ({
  organization_id: organizationId,
  property_id: propertyId,
  title: property.title,
  stage: 'interested',
  priority: 'medium',
  estimated_roi: estimateRoi(analysis),
  expected_monthly_rent: property.expectedRent ?? null,
  renovation_budget: safeNumber(analysis.renovationROI.estimatedCost),
  notes: `Generated by Deal Analyzer at ${analysis.analyzedAt}. Recommendation: ${analysis.recommendation}.`,
})

const isCreatedByColumnMissing = (error: { message?: string; details?: string } | null) => {
  const hint = `${error?.message ?? ''} ${error?.details ?? ''}`.toLowerCase()
  return hint.includes('created_by') && hint.includes('column')
}

const insertWithOptionalCreatedBy = async <T extends Record<string, unknown>>(
  table: string,
  payload: T,
  userId: string,
) => {
  const client = getSupabaseClient()
  if (!client) {
    throw new Error('Supabase is not configured.')
  }

  const withCreatedBy = {
    ...payload,
    created_by: userId,
  }

  const firstAttempt = await client.from(table).insert([withCreatedBy]).select('id').single()
  if (!firstAttempt.error) {
    return firstAttempt
  }

  if (!isCreatedByColumnMissing(firstAttempt.error)) {
    return firstAttempt
  }

  return client.from(table).insert([payload]).select('id').single()
}

const insertNote = async (payload: {
  organization_id: string
  opportunity_id: string
  content: string
}) => {
  const client = getSupabaseClient()
  if (!client) {
    throw new Error('Supabase is not configured.')
  }

  return client.from('notes').insert([payload]).select('id').single()
}

const resolveOrganizationContext = async (): Promise<{ organizationId: string; userId: string }> => {
  const client = getSupabaseClient()
  if (!client) {
    throw new Error('Supabase is not configured.')
  }

  const { data: userData } = await client.auth.getUser()
  const user = userData as AuthUser | null
  if (!user?.id) {
    throw new Error('No authenticated user is available for persistence.')
  }

  const profileByIdResult = await client
    .from('profiles')
    .select('id,user_id,organization_id')
    .eq('id', user.id)
    .maybeSingle()

  let profile = (profileByIdResult.data as ProfileRow | null) ?? null

  if (!profile && !profileByIdResult.error) {
    const profileByUserIdResult = await client
      .from('profiles')
      .select('id,user_id,organization_id')
      .eq('user_id', user.id)
      .maybeSingle()

    if (profileByUserIdResult.error) {
      throw new Error(profileByUserIdResult.error.message)
    }

    profile = (profileByUserIdResult.data as ProfileRow | null) ?? null
  }

  if (profileByIdResult.error) {
    throw new Error(profileByIdResult.error.message)
  }

  if (!profile?.organization_id) {
    throw new Error('No active organization found for the authenticated user profile.')
  }

  return {
    organizationId: profile.organization_id,
    userId: user.id,
  }
}

export const persistDealAnalyzerResult = async (
  property: Property,
  analysis: InvestmentAnalysis,
): Promise<DealPersistenceResult> => {
  const client = getSupabaseClient()
  if (!client) {
    return { persisted: false, reason: 'Supabase is unavailable. Running in local-only mode.' }
  }

  try {
    const { organizationId, userId } = await resolveOrganizationContext()

    const { data: propertyData, error: propertyError } = await insertWithOptionalCreatedBy(
      'properties',
      mapPropertyToInsert(organizationId, property),
      userId,
    )

    if (propertyError || !propertyData) {
      throw new Error(propertyError?.message || 'Failed to create property.')
    }

    const propertyId = (propertyData as { id: string }).id

    const { data: opportunityData, error: opportunityError } = await insertWithOptionalCreatedBy(
      'opportunities',
      mapOpportunityToInsert(organizationId, propertyId, property, analysis),
      userId,
    )

    if (opportunityError || !opportunityData) {
      throw new Error(opportunityError?.message || 'Failed to create opportunity.')
    }

    const opportunityId = (opportunityData as { id: string }).id

    const { data: noteData, error: noteError } = await insertNote({
      organization_id: organizationId,
      opportunity_id: opportunityId,
      content: JSON.stringify(analysis),
    })

    if (noteError || !noteData) {
      throw new Error(noteError?.message || 'Failed to create analysis note snapshot.')
    }

    await replaceAiFindingsForOpportunity(client, analysis, organizationId, opportunityId)

    return {
      persisted: true,
      organizationId,
      propertyId,
      opportunityId,
      noteId: (noteData as { id: string }).id,
    }
  } catch (error) {
    return {
      persisted: false,
      reason: error instanceof Error ? error.message : 'Unknown persistence error.',
    }
  }
}
